packages:
  - packages/*

catalogs:
  dev:
    '@commitlint/cli': ^20.1.0
    '@commitlint/config-conventional': ^20.0.0
    '@lerna-lite/cli': ^4.9.2
    '@lerna-lite/publish': ^4.9.2
    '@meteorlxy/eslint-config': ^6.8.5
    '@meteorlxy/prettier-config': ^6.8.5
    '@meteorlxy/tsconfig': ^6.8.5
    '@vitest/coverage-istanbul': ^4.0.10
    eslint: ^9.39.1
    husky: ^9.1.7
    lint-staged: ^16.2.6
    prettier: ^3.6.2
    rimraf: ^6.1.0
    sort-package-json: ^3.4.0
    tsdown: ^0.16.5
    typescript: ^5.9.3
    vitest: ^4.0.10

  dev-test:
    '@types/markdown-it-emoji': ^3.0.1
    '@vue/shared': ^3.5.24
    markdown-it-anchor: ^9.2.0
    markdown-it-emoji: ^3.0.0

  prod:
    '@types/markdown-it': ^14.1.2
    gray-matter: ^4.0.3
    markdown-it: ^14.1.0
