import type Token from 'markdown-it/lib/token';
import { htmlEscape } from './html-escape';

/**
 * Resolve header title from markdown-it token
 *
 * Typically using the next token of `heading_open` token
 */
export const resolveTitleFromToken = (
  token: Token,
  {
    shouldAllowHtml,
    shouldEscapeText,
  }: {
    shouldAllowHtml: boolean;
    shouldEscapeText: boolean;
  },
): string => {
  // children of the token contains the parsed result of the heading title
  const children = token.children ?? [];

  // type of tokens to be included in the heading title
  const titleTokenTypes = ['text', 'emoji', 'code_inline'];

  // include 'html_inline' or not
  if (shouldAllowHtml) {
    titleTokenTypes.push('html_inline');
  }

  // filter the token type to be included in the title
  const titleTokens = children.filter(
    (item) =>
      titleTokenTypes.includes(item.type) &&
      // filter permalink symbol that generated by markdown-it-anchor
      !item.meta?.isPermalinkSymbol,
  );

  // get title from tokens
  return titleTokens
    .reduce((result, item) => {
      if (shouldEscapeText) {
        // escape the content of 'code_inline' and 'text'
        if (item.type === 'code_inline' || item.type === 'text') {
          return `${result}${htmlEscape(item.content)}`;
        }
      }

      // keep the content of 'emoji' and 'html_inline'
      return `${result}${item.content}`;
    }, '')
    .trim();
};
